name: 🚀 Deploy
# l'action deploy va etre executée après chaque push ou pull request sur les branches main et dev
on:
  push:
    branches:
      - develop
      - ope
  pull_request: {}

#permissions
permissions:
  actions: write
  contents: read

#les jobs chaque job correspond à une action
jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # arret si un 2 push est lancé
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔬 Lint
        run: npm run lint


  build:
    name: 🐳 build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy:
    name: 🚀 Deploy
    runs-on: [self-hosted]
    # signifie que cette action sera exécutée que si les actions dans le tableau needs sont executée
    needs: [lint,build]
    # only build/deploy main branch on pushes
    if: ${{ (github.ref == 'refs/heads/ope' || github.ref == 'refs/heads/develop') && github.event_name == 'push' }}
    # env:
    #   APP_ENV: ${{ secrets.APP_ENV }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🚀 Run Docker Compose on Production
        if: ${{ github.ref == 'refs/heads/ope' }}
        env:
          APP_ENV: ${{ secrets.APP_ENV }}
        run: |
          docker pull josephaxelad/gdo-front:ope
          docker compose -f docker-compose.yaml up -d --build
          docker system prune --all --volumes --force

      - name: 🚀 Run Docker Compose on Staging
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          APP_ENV: ${{ secrets.APP_ENV_RE7 }}
        run: |
          docker pull josephaxelad/gdo-front:latest
          docker compose -f docker-compose.staging.yaml up -d
          docker system prune --all --volumes --force
